# Generated by Django 4.1.2 on 2022-10-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("car_id", models.AutoField(primary_key=True, serialize=False)),
                ("car_x", models.IntegerField()),
                ("car_y", models.IntegerField()),
                ("car_control", models.IntegerField()),
            ],
        ),
    ]
