# Generated by Django 2.2.28 on 2022-10-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_IP',
            field=models.TextField(default=''),
        ),
    ]
