# Generated by Django 2.2.28 on 2022-10-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_car', '0002_car_car_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Des',
            fields=[
                ('des_id', models.AutoField(primary_key=True, serialize=False)),
                ('des_name', models.TextField()),
                ('des_description', models.TextField()),
                ('des_x', models.IntegerField()),
                ('des_y', models.IntegerField()),
            ],
        ),
    ]
