# Generated by Django 2.2.28 on 2022-11-01 22:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('remote_car', '0003_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_lastTimeConnected',
            field=models.TimeField(default=datetime.datetime(2022, 11, 1, 22, 12, 10, 658916, tzinfo=utc)),
        ),
    ]
