# Generated by Django 2.2.28 on 2022-11-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_car', '0004_car_car_lasttimeconnected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_lastTimeConnected',
            field=models.TimeField(default=1667341229.7352011),
        ),
    ]
