# Generated by Django 2.2.28 on 2022-11-01 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_car', '0005_auto_20221101_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_lastTimeConnected',
            field=models.TimeField(default=datetime.datetime(2022, 11, 1, 23, 22, 47, 407850)),
        ),
    ]
