# Generated by Django 2.2.28 on 2022-11-02 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_car', '0006_auto_20221101_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_lastTimeConnected',
            field=models.TextField(default=datetime.datetime(2022, 11, 2, 20, 59, 20, 603849)),
        ),
    ]
