# Generated by Django 2.2.28 on 2022-11-03 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_car', '0007_auto_20221102_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='des',
            name='des_disable',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_lastTimeConnected',
            field=models.TextField(default=datetime.datetime(2022, 11, 3, 11, 42, 14, 623103)),
        ),
    ]
