# Generated by Django 3.2.16 on 2022-11-13 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_car', '0008_auto_20221103_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_lastTimeConnected',
            field=models.TextField(default=datetime.datetime(2022, 11, 13, 21, 44, 46, 579104)),
        ),
    ]
