# Generated by Django 3.2.16 on 2022-11-13 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_car', '0009_alter_car_car_lasttimeconnected'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_name',
            field=models.TextField(default='iCart'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_lastTimeConnected',
            field=models.TextField(default=datetime.datetime(2022, 11, 13, 21, 49, 1, 696320)),
        ),
    ]
