# Generated by Django 3.2.19 on 2025-01-06 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_car', '0010_auto_20221113_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('AMRID', models.IntegerField(blank=True, null=True)),
                ('AMRState', models.TextField(default='Idle')),
                ('isActive', models.BooleanField(default=True)),
                ('taskID', models.IntegerField(blank=True, default=None, null=True)),
                ('loc_x', models.FloatField(blank=True, null=True)),
                ('loc_y', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, default=0, null=True)),
                ('AngOrientation', models.FloatField(blank=True, default=0, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('batterySoC', models.FloatField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='car_lastTimeConnected',
            field=models.TextField(default=datetime.datetime(2025, 1, 6, 15, 55, 59, 223127)),
        ),
    ]
