# Generated by Django 3.2.19 on 2025-01-06 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_car', '0011_auto_20250106_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='id',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='recordID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_lastTimeConnected',
            field=models.TextField(default=datetime.datetime(2025, 1, 6, 15, 58, 23, 860750)),
        ),
    ]
