# Generated by Django 3.2.19 on 2025-01-12 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_car', '0012_auto_20250106_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvData',
            fields=[
                ('recordID', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='car_control',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_lastTimeConnected',
            field=models.TextField(default=datetime.datetime(2025, 1, 12, 20, 50, 58, 702795)),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
