# Generated by Django 3.2.19 on 2025-01-12 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_car', '0014_auto_20250112_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_lastTimeConnected',
            field=models.TextField(default=datetime.datetime(2025, 1, 12, 21, 52, 25, 751187)),
        ),
    ]
